apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Splunk Logger
  description: Splunk Logger Plugin for the Reekoh IoT Platform
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Logger
  price: 0
  tags:
    - logger
    - splunk

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      token:
        label: Token
        type: Password
        maxLength: 1000
        required: true
        help: Please provide your Splunk Token.
      url:
        label: URL
        type: String
        maxLength: 1000
        required: true
        help: Please provide your Splunk instance URL.